### ISSUE TITLE
Getter and setter for timestamp of raised events

### ISSUE THREAD

**Issue by juan3036** [unicesi/pascani#1]
I would be great that the timestamp associated with every event could be getted in order to facilitate the construction of reports. Additionally, a setter for this attribute is also desired. In multi-threading some events are raised in different orders but you need to establish some specific order in the events to construct a report more easily.

**Comment by jachinte** [comment]
Since the timestamp field in class Event is protected, I understand the necessity of a getter method. However I am not sure about a setter method; this would undermine the integrity of the object. The timestamp field represents the stamp of time when the event is raised, therefore updating it does not seem like a valid request. Perhaps you need to add an additional field to support the desired behavior.
