### ISSUE TITLE
CurrentMillis instead of nanoTime

### ISSUE THREAD

**Issue by juan3036** [unicesi/pascani#2]
Hi.
Currently Pascani uses nanoTime in a great part of the methods, especially in the timestamp method that registers the moment when a event is raised. However, according to the Java API documentation the value returned by the nanoTime method represents nanoseconds since some fixed but arbitrary origin time. Therefore, times registered in different JVM's might arise inconsistencies. Since currentMillis establish as fixed point midnight, January 1, 1970 UTC. I suggest to change to currentMillis to avoid unexpected possible inconsistencies. 
Thanks for your contribution.

**Comment by jachinte** [comment]
Hi @juan3036,
You are completly right about this matter. In the case of Pascani, accuracy is much more important than precision. This is unfortunate, if you ask me, because after all we are measuring system performance and this has a huge impact on applications with small execution times. However, as Pascani is intended to be used in distributed environments, it has to be this way. I'll be updating the repo as soon as possible with the necessary changes.

As you pointed earlier via email, here are some facts about `System.nanoTime` supporting this decision:
- This method can only be used to measure elapsed time and **is not related to any other notion of system or wall-clock time**. The value returned represents nanoseconds since some fixed but **arbitrary origin time** (perhaps in the future, so values may be negative). The same origin is used by all invocations of this method in an instance of a Java virtual machine; **other virtual machine instances are likely to use a different origin**.
- The values returned by this method become meaningful only when the difference between two such values, **obtained within the same instance of a Java virtual machine**, is computed.

**Comment by jachinte** [comment]
After carefully reviewing the library, only one class makes use of the `System.nanoTime`method, which is surprisingly good. The rest of the classes always receive the epoch times as parameters; so, you just need to change the way you are measuring execution times.

One last thought, I still think elapsed times should be measured using nanoseconds, as long as the start and end times are measured within the same JVM.

**Comment by juan3036** [comment]
Good to hear that. Thanks for the advice; however, I decided to change to currentMillis method in all classes where I take the time measures. I suppose that the affected method is the recently exposed timeStamp associated to all events.

**Comment by jachinte** [comment]
Yeah, that's the only one!
